spring:
  application:
    name: MarkusAI Backend
  jpa:
    hibernate:
       ddl-auto: update
    defer-datasource-initialization: true

  datasource:
    url: ${AZURE_DB_URL}
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  data:
    jdbc:
      dialect: sql_server
  config:
    import: optional:file:.env[.properties]
clerk:
  api:
    url: ${CLERK_BACKEND_API_URL}
    key: ${CLERK_SECRET_KEY}
openai:
  api:
    key: ${OPENAI_API_KEY}